name: Deploy - Full

run-name: "${{ inputs.environment }} | Terraform Apply? = ${{ inputs.is_deployment }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        default: "dev"
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - pre-prod
          - prod
      is_deployment:
        default: false
        type: boolean
        description: "Terraform Apply?"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deductions-ci:
    name: Deploy Deductions Infrastructure
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack: deductions
      backend_key_alias: deductions-infra-${{ inputs.environment }}
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
      lambdas_to_build: true
    secrets: inherit

  deductions-cross-account:
    name: Deploy Deductions Cross Account Infrastructure
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack: deductions-cross-account
      backend_key_alias: deductions-infra-cross-account-${{ inputs.environment }}
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
      lambdas_to_build: true
    secrets: inherit

  deductions-dashboard-ci:
    name: Deploy Deductions Dashboard Infrastructure
    uses: ./.github/workflows/deploy-stack.yml
    needs: [deductions-ci]
    with:
      stack: deductions-dashboard
      backend_key_alias: deductions-infra-dashboard-${{ inputs.environment }}
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit

  mesh-forwarder-ci:
    name: Deploy MESH Forwarder Infrastructure
    needs: [deductions-ci, deductions-cross-account]
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack: mesh-forwarder
      ecr_alias: deductions/mesh-forwarder
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit

  pds-adaptor-ci:
    name: Deploy PDS Adaptor Infrastructure
    needs: [deductions-ci, deductions-cross-account]
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack: pds-adaptor
      ecr_alias: deductions/pds-adaptor
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit

  re-registration-service-ci:
    name: Deploy Re-Registration Service Infrastructure
    needs: [deductions-ci, deductions-cross-account]
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack: re-registration-service
      ecr_alias: repo/re-registration-service
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit

  suspension-service-ci:
    name: Deploy Suspension Service Infrastructure
    needs: [deductions-ci, deductions-cross-account]
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack: suspension-service
      ecr_alias: repo/suspension-service
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit

  nems-event-processor-ci:
    name: Deploy NEMS Event Processor Infrastructure
    needs: [deductions-ci, deductions-cross-account]
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack: nems-event-processor
      ecr_alias: deductions/nems-event-processor
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit

  ehr-repo-ci:
    name: EHR Repo Infrastructure
    uses: ./.github/workflows/deploy-stack.yml
    needs: [deductions-ci, deductions-cross-account]
    with:
      stack: ehr-repo
      ecr_alias: deductions/ehr-repo
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit

  ehr-out-service-ci:
    name: Deploy EHR Out Service Infrastructure
    uses: ./.github/workflows/deploy-stack.yml
    needs: [deductions-ci, deductions-cross-account]
    with:
      stack: ehr-out-service
      ecr_alias: deductions/ehr-out-service
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit

  ehr-transfer-service-ci:
    name: Deploy EHR Transfer Service Infrastructure
    uses: ./.github/workflows/deploy-stack.yml
    needs: [deductions-ci, deductions-cross-account]
    with:
      stack: ehr-transfer-service
      ecr_alias: deductions/ehr-transfer-service
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit

  gp2gp-messenger-ci:
    name: Deploy GP2GP Messenger Infrastructure
    uses: ./.github/workflows/deploy-stack.yml
    needs: [deductions-ci, deductions-cross-account]
    with:
      stack: gp2gp-messenger
      ecr_alias: deductions/gp2gp-messenger
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit

  mhs-ci:
    name: Deploy MHS Infrastructure
    uses: ./.github/workflows/deploy-stack.yml
    needs: [deductions-ci, deductions-cross-account]
    with:
      stack: mhs
      backend_key_alias: mhs-${{ inputs.environment }}-repo
      environment: ${{ inputs.environment }}
      is_deployment: ${{ inputs.is_deployment }}
    secrets: inherit
